<?php if ( ! defined( 'ABSPATH' ) ) { exit; }
if ( isset($_GET['imported']) ) { echo '<div class="notice notice-success inline"><p>' . esc_html__('Theme settings imported successfully.','wpraffle-theme') . '</p></div>'; }
if ( isset($_GET['import_error']) ) { echo '<div class="notice notice-error inline"><p>' . esc_html__('The settings file could not be imported. Check that it is a WPRaffle Theme JSON export.','wpraffle-theme') . '</p></div>'; }
?>
<div class="wprt-dashboard-grid">
<section class="wpr-panel"><div class="wprt-card-heading"><div><span class="dashicons dashicons-download"></span><h2><?php esc_html_e('Export settings','wpraffle-theme'); ?></h2></div></div><p><?php esc_html_e('Download the current theme configuration as JSON for staging, backup or another WPRaffle site.','wpraffle-theme'); ?></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="wprt_export_settings"><?php wp_nonce_field('wprt_export_settings'); ?><button class="button button-primary"><?php esc_html_e('Download Settings JSON','wpraffle-theme'); ?></button></form></section>
<section class="wpr-panel"><div class="wprt-card-heading"><div><span class="dashicons dashicons-upload"></span><h2><?php esc_html_e('Import settings','wpraffle-theme'); ?></h2></div></div><p><?php esc_html_e('Restore a WPRaffle Theme JSON export. Existing theme settings will be replaced, but posts, products and competition data are untouched.','wpraffle-theme'); ?></p><form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="wprt_import_settings"><?php wp_nonce_field('wprt_import_settings'); ?><input type="file" name="settings_file" accept="application/json,.json" required><p><button class="button"><?php esc_html_e('Import Settings','wpraffle-theme'); ?></button></p></form></section>
</div>
<section class="wpr-panel"><div class="wprt-card-heading"><div><span class="dashicons dashicons-admin-tools"></span><h2><?php esc_html_e('Developer shortcuts','wpraffle-theme'); ?></h2></div></div><div class="wprt-quick-actions"><a href="<?php echo esc_url(admin_url('themes.php?page=wpraffle-theme-settings&tab=custom-code')); ?>"><span class="dashicons dashicons-editor-code"></span><strong><?php esc_html_e('Custom Code','wpraffle-theme'); ?></strong><small><?php esc_html_e('CSS and JavaScript overrides.','wpraffle-theme'); ?></small></a><a href="<?php echo esc_url(admin_url('themes.php?page=wpraffle-theme-settings&tab=optimization')); ?>"><span class="dashicons dashicons-performance"></span><strong><?php esc_html_e('Optimisation','wpraffle-theme'); ?></strong><small><?php esc_html_e('Asset and performance controls.','wpraffle-theme'); ?></small></a><a href="<?php echo esc_url(admin_url('themes.php?page=wpraffle-theme-settings&tab=status')); ?>"><span class="dashicons dashicons-dashboard"></span><strong><?php esc_html_e('System Status','wpraffle-theme'); ?></strong><small><?php esc_html_e('Environment and dependency checks.','wpraffle-theme'); ?></small></a></div></section>
<section class="wpr-panel">
<div class="wprt-card-heading"><div><span class="dashicons dashicons-admin-appearance"></span><h2><?php esc_html_e('Child Theme Generator','wpraffle-theme'); ?></h2></div></div>
<p><?php esc_html_e('Download a clean WPRaffle child theme for update-safe PHP and CSS customisations.','wpraffle-theme'); ?></p>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
<input type="hidden" name="action" value="wprt_generate_child_theme"><?php wp_nonce_field('wprt_generate_child_theme'); ?>
<label><strong><?php esc_html_e('Child theme name','wpraffle-theme'); ?></strong><br><input type="text" name="child_name" value="WPRaffle Child" class="regular-text"></label>
<p><button class="button button-primary"><?php esc_html_e('Download Child Theme ZIP','wpraffle-theme'); ?></button></p>
</form>
</section>
